npmMinimalAgeGate: 3d
enableScripts: true
nodeLinker: node-modules
approvedGitRepositories:
  - "**"

npmScopes:
  abinnovision:
    npmAlwaysAuth: false
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
